/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package equationframe;

/**
 *
 * @author Nathan
 */
public class EquationFrame extends javax.swing.JFrame {

    /**
     * Creates new form EquationFrame
     */
    public EquationFrame() {
        initComponents();
        
        respLabel.setVisible(false);
        deltaLabel.setVisible(false);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calculateButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        aValue = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        bValue = new javax.swing.JSpinner();
        cValue = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bRepresentation = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        aRepresentation = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cRepresentation = new javax.swing.JLabel();
        respLabel = new javax.swing.JLabel();
        deltaLabel = new javax.swing.JLabel();
        rootLabel = new javax.swing.JLabel();
        respostaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        calculateButton.setText("Calculate Δ");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Δ =");

        aValue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        aValue.setModel(new javax.swing.SpinnerNumberModel());
        aValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                aValueStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("x² +");

        bValue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bValue.setModel(new javax.swing.SpinnerNumberModel());
        bValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                bValueStateChanged(evt);
            }
        });

        cValue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cValue.setModel(new javax.swing.SpinnerNumberModel());
        cValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cValueStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("x +");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("= 0");

        bRepresentation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bRepresentation.setForeground(new java.awt.Color(255, 0, 0));
        bRepresentation.setText("B");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("² - 4 .");

        aRepresentation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        aRepresentation.setForeground(new java.awt.Color(255, 0, 0));
        aRepresentation.setText("A");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText(".");

        cRepresentation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cRepresentation.setForeground(new java.awt.Color(255, 0, 0));
        cRepresentation.setText("C");

        respLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        respLabel.setText("The Delta of equation is");

        deltaLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        deltaLabel.setForeground(new java.awt.Color(0, 0, 255));
        deltaLabel.setText("?");

        respostaLabel.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(calculateButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(32, 32, 32)
                                            .addComponent(bRepresentation)
                                            .addGap(3, 3, 3)
                                            .addComponent(jLabel6)
                                            .addGap(4, 4, 4)
                                            .addComponent(aRepresentation))
                                        .addComponent(jLabel1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cRepresentation)
                                    .addGap(26, 26, 26))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(251, 251, 251)
                                        .addComponent(rootLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(respLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(deltaLabel))
                                    .addComponent(respostaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(bValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bRepresentation)
                    .addComponent(jLabel6)
                    .addComponent(aRepresentation)
                    .addComponent(jLabel9)
                    .addComponent(cRepresentation))
                .addGap(29, 29, 29)
                .addComponent(calculateButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respLabel)
                    .addComponent(deltaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(respostaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rootLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        
        respLabel.setVisible(true);
        deltaLabel.setVisible(true);
        
        int a = (int) aValue.getValue();
        int b = (int) bValue.getValue();
        int c = (int) cValue.getValue();
        
        String stringA = Integer.toString(a);
        String stringB = Integer.toString(b);
        String stringC = Integer.toString(c);
        
        aRepresentation.setText(stringA);
        bRepresentation.setText(stringB);
        cRepresentation.setText(stringC);
        
        String deltaValue = Integer.toString(b * b - 4 * a * c);
        deltaLabel.setText(deltaValue);
        int deltaNumber = Integer.parseInt(deltaValue);
        
        if (deltaNumber >= 0) {
            respostaLabel.setText("Has real roots");
        } else {
            respostaLabel.setText("Has no real roots");
        }
        
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void bValueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_bValueStateChanged
        
        int a = (int) aValue.getValue();
        int b = (int) bValue.getValue();
        int c = (int) cValue.getValue();
        
        String stringA = Integer.toString(a);
        String stringB = Integer.toString(b);
        String stringC = Integer.toString(c);
        
        aRepresentation.setText(stringA);
        bRepresentation.setText(stringB);
        cRepresentation.setText(stringC);
        
    }//GEN-LAST:event_bValueStateChanged

    private void cValueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cValueStateChanged
        
        int a = (int) aValue.getValue();
        int b = (int) bValue.getValue();
        int c = (int) cValue.getValue();
        
        String stringA = Integer.toString(a);
        String stringB = Integer.toString(b);
        String stringC = Integer.toString(c);
        
        aRepresentation.setText(stringA);
        bRepresentation.setText(stringB);
        cRepresentation.setText(stringC);
        
    }//GEN-LAST:event_cValueStateChanged

    private void aValueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_aValueStateChanged
        
        int a = (int) aValue.getValue();
        int b = (int) bValue.getValue();
        int c = (int) cValue.getValue();
        
        String stringA = Integer.toString(a);
        String stringB = Integer.toString(b);
        String stringC = Integer.toString(c);
        
        aRepresentation.setText(stringA);
        bRepresentation.setText(stringB);
        cRepresentation.setText(stringC);
        
    }//GEN-LAST:event_aValueStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EquationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EquationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EquationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EquationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EquationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aRepresentation;
    private javax.swing.JSpinner aValue;
    private javax.swing.JLabel bRepresentation;
    private javax.swing.JSpinner bValue;
    private javax.swing.JLabel cRepresentation;
    private javax.swing.JSpinner cValue;
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel deltaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel respLabel;
    private javax.swing.JLabel respostaLabel;
    private javax.swing.JLabel rootLabel;
    // End of variables declaration//GEN-END:variables
}
